export const GET_ALL_PRICES = "GET_ALL_PRICES";
export const GET_ALL_PRICES_FAILURE = "GET_ALL_PRICES_FAILURE";
export const START_WASH = "START_WASH";
export const WASH_SUCCESS = "WASH_SUCCESS";
export const WASH_FAILURE = "WASH_FAILURE";